#%RAML 1.0

title: DMS API
version: v1
baseUri: http://dms.codenetix.com/api/{version}

types: !include allDataTypes.raml

resourceTypes:
  PaginationAndPost: !include resourceTypes/paginationAndPost.raml
  PaginationCollection: !include resourceTypes/paginationCollection.raml
  Collection: !include resourceTypes/collection.raml
  Item: !include resourceTypes/item.raml
  ItemWithPatch: !include resourceTypes/itemWithPatch.raml
  Post: !include resourceTypes/post.raml

/users:
  type:
    PaginationAndPost:
      responseItem: User
      postRequestItem: UserPostRequest
      examplesJson: !include examples/Users.json
      metaExample: '{}'
      example: !include examples/User.json
  /current:
    type:
      Item:
        responseItem: User
        putRequestItem: UserPutRequest
        metaExample: '{}'
        example: !include examples/User.json
  /{id}:
    uriParameters:
      id:
        type: integer
        example: 1
        default: 1
    type:
      Item:
        responseItem: User
        putRequestItem: UserPutRequest
        metaExample: '{}'
        example: !include examples/User.json
/templates:
  type:
    PaginationAndPost:
      responseItem: Template
      postRequestItem: TemplateRequest
      examplesJson: !include examples/Templates.json
      metaExample: '{}'
      example: !include examples/Template.json
  /{id}:
    uriParameters:
      id:
        type: integer
        example: 1
        default: 1
    type:
      Item:
        responseItem: Template
        putRequestItem: TemplateRequest
        metaExample: '{"documentsLinked": 10}'
        example: !include examples/Template.json
    /attributes:
      type:
        PaginationCollection:
          responseItem: Attribute
          postRequestItem: AttributeRequest
          examplesJson: !include examples/Attributes.json
          metaExample: '{}'
          example: !include examples/Attribute.json

#/attributes:
#  type:
#    Post:
#      responseItem: Attribute
#      postRequestItem: AttributeRequest
#      metaExample: '{}'
#      example: !include examples/Attribute.json
#  /{attributeId}:
#    uriParameters:
#      attributeId:
#        type: integer
#        example: 1
#        default: 1
#    type:
#      Item:
#        responseItem: Attribute
#        putRequestItem: AttributeRequest
#        metaExample: '{}'
#        example: !include examples/Attribute.json

/documents:
  type:
    PaginationAndPost:
      responseItem: Document
      postRequestItem: DocumentPostRequest
      examplesJson: !include examples/Documents.json
      metaExample: '{}'
      example: !include examples/Document.json
  get:
    queryParameters:
      filters[name]?:
        type: string
        example: match
      filters[id]?:
        type: integer
        example: 1
      filters[ids]?:
        type: string
        example: 1,2,3
      filters[ownerId]?:
        type: integer
        example: 1
      filters[templateIds]?:
        type: string
        example: 1,2,3
      filters[labelIds]?:
        type: string
        example: 1,2,3
      filters[archived]?:
        type: boolean
        example: true
      filters[createdAt.from]?:
        type: integer
        example: 1527231850
      filters[createdAt.to]?:
        type: integer
        example: 1527231850
      filters[updatedAt.from]?:
        type: integer
        example: 1527231850
      filters[updatedAt.to]?:
        type: integer
        example: 1527231850
  delete:
    queryParameters:
      ids:
        description: Delete selected elements
        type: string
        example: 1,2
        default: 1,2
    responses:
      204:
        description: Deleted
  patch:
    queryParameters:
      ids:
        description: Update selected elements
        type: string
        default: 1,2
        example: 1,2
    body:
      application/json:
        type: object[] #raml mock can't work with array of concrete object in request
        example: !include examples/DocumentPatchRequests.json
    responses:
      200:
        description: Updated
        body:
          application/json:
            type: Document[]
            example: !include examples/Documents.json
  /{id}:
    uriParameters:
      id:
        type: integer
        example: 1
        default: 1
    type:
      ItemWithPatch:
        responseItem: Document
        putRequestItem: DocumentPutRequest
        patchRequestItem: DocumentPatchRequest
        metaExample: '{}'
        example: !include examples/Document.json
    /versions:
      type:
        PaginationCollection:
          responseItem: DocumentVersion
          examplesJson: !include examples/DocumentVersions.json

/documentVersions:
  type:
    Post:
      responseItem: DocumentVersion
      postRequestItem: DocumentVersionRequest
      metaExample: '{}'
      example: !include examples/DocumentVersion.json
  /{versionId}:
    uriParameters:
      versionId:
        type: integer
        example: 1
        default: 1
    type:
      Item:
        responseItem: DocumentVersion
        putRequestItem: DocumentVersionRequest
        metaExample: '{}'
        example: !include examples/DocumentVersion.json

/types:
  type:
    Collection:
      responseItem: Type
      examplesJson: !include examples/Types.json

/labels:
  type:
    PaginationAndPost:
      responseItem: Label
      postRequestItem: LabelRequest
      examplesJson: !include examples/Labels.json
      metaExample: '{}'
      example: !include examples/Label.json
  /{id}:
    uriParameters:
      id:
        type: integer
        example: 1
        default: 1
    type:
      Item:
        responseItem: Label
        putRequestItem: LabelRequest
        metaExample: '{}'
        example: !include examples/Label.json

/roles:
  type:
    PaginationAndPost:
      responseItem: Role
      postRequestItem: RoleRequest
      examplesJson: !include examples/Roles.json
      metaExample: '{}'
      example: !include examples/Role.json
  /{id}:
    uriParameters:
      id:
        type: integer
        example: 1
        default: 1
    type:
      Item:
        responseItem: Role
        putRequestItem: RoleRequest
        metaExample: '{}'
        example: !include examples/Role.json

/oauth:
  /token:
    post:
      body:
        application/json:
          type: AuthRequest
      responses:
        200:
          description:
            Success Auth
          body:
            application/json:
              Auth
  /logout:
    post:
      responses:
        204:
          description:
            Success logout
  /resetEmail:
    post:
      body:
        application/json:
          type: ResetEmailRequest
      responses:
        204:
          description:
            Email was sent
  /resetPassword/{hash}:
    uriParameters:
      hash:
        type: string
        example: f5f2f2ec355835af36fea2ad93ac3de6
        default: f5f2f2ec355835af36fea2ad93ac3de6
    post:
      body:
        application/json:
          type: ResetPasswordRequest
      responses:
        204:
          description:
            Success

/permissionGroups:
  type:
    Collection:
      responseItem: PermissionGroup
      examplesJson: !include examples/PermissionGroups.json

/files:
  post:
    body:
      multipart/form-data:
        properties:
          file:
            description: The file to be uploaded.
            required: true
            type: file
    responses:
      201:
        description:
          Success Upload
        body:
          application/json:
            type: object
            properties:
              id: integer
            example:
              id: 1

/logs:
  type:
    PaginationCollection:
      responseItem: Log
      examplesJson: !include examples/Logs.json
