#%RAML 1.0 DataType

type: object
properties:
  id: integer
  ownerId: integer
  substituteDocumentId: integer
  actualVersion: !include documentVersion.raml
  owner: !include user.raml
  version: integer
  createdAt: integer
  updatedAt: integer

example: !include ../examples/Document.json