#%RAML 1.0 ResourceType

get:
  queryParameters:
    sortField?:
      description: Sorting field
      type: string
      example: id
    sortDirection?:
      description: Sorting direction
      enum: [desc, asc]
      default: asc
      example: desc
    with?:
      description: Expand embeded entityes
      type: string
      example: user,type
  responses:
    200:
      description:
        List of items
      body:
        application/json:
          type: <<responseItem>>[]
          example: <<examplesJson>>
