#%RAML 1.0 ResourceType
get:
  queryParameters:
    with?:
      description: Expand embeded entityes
      type: string
      example: user,type
  responses:
    200:
      description:
        Singular item
      body:
        application/json:
          <<responseItem>>

put:
  queryParameters:
    with?:
      description: Expand embeded entityes
      type: string
      example: user,type
  body:
    application/json:
      <<putRequestItem>>
  responses:
    200:
      description:
        Updated item
      body:
        application/json:
          <<responseItem>>

delete:
  responses:
    204:
      description:
        No content
