#%RAML 1.0 ResourceType
get:
  queryParameters:
    with?:
      description: Expand embeded entityes
      type: string
      example: user,type
  responses:
    200:
      description:
        Singular item
      body:
        application/json:
          type: object
          properties:
            data:
              <<responseItem>>
            meta: object
          example: |
            {
              "meta": <<metaExample>>,
              "data": <<example>>
            }

put:
  queryParameters:
    with?:
      description: Expand embeded entityes
      type: string
      example: user,type
  body:
    application/json:
      <<putRequestItem>>
  responses:
    200:
      description:
        Updated item
      body:
        application/json:
          type: object
          properties:
            data:
              <<responseItem>>
            meta: object
          example: |
            {
              "meta": <<metaExample>>,
              "data": <<example>>
            }

delete:
  responses:
    204:
      description:
        No content
patch:
  queryParameters:
    with?:
      description: Expand embeded entityes
      type: string
      example: user,type
  body:
    application/json:
      <<patchRequestItem>>
  responses:
    200:
      description:
        Updated item
      body:
        application/json:
          type: object
          properties:
            data:
              <<responseItem>>
            meta: object
          example: |
            {
              "meta": <<metaExample>>,
              "data": <<example>>
            }
