#%RAML 1.0 DataType

type: object
properties:
  id: integer
  type:
    type: !include type.raml
  name: string
  table:
    type: object
    properties:
      rows:
        type: array
        items:
          type: object
          properties:
            name: string
            columns:
              type: array
              items:
                type: object
                properties:
                  isLocked: boolean
                  type: !include type.raml
      columns:
        type: object
        properties:
          name: string
          type: !include type.raml

example: !include ../examples/Attribute.json
