#%RAML 1.0 DataType

type: object
properties:
  id: integer
  name:
    type: string
    enum: ['String', 'Numeric', 'Boolean', 'Table', 'Value with deviations']
  machineName:
    type: string
    enum: ['string', 'numeric', 'boolean', 'table', 'valueWithDeviations']
example: !include ../examples/Type.json
